#!/bin/bash

# Check if LONG_URL begins with 'http' and contains at least one '.'
# char, which are Cloudflare requirement for valid redirects.
LONG_URL="$1"
if [[ $LONG_URL != "http"*"://"*"."* ]]; then
  echo "Error: Your input LONG_URL ('$LONG_URL') is invalid."
  echo -e "Hints:\n- Does it start with 'http'?\n- Does it contain a '.'?"
  exit 1
fi
